import React from 'react';
import { DISCLAIMER_TEXT } from '../disclaimer/DisclaimerContent';

export function DisclaimerView() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-8 sm:py-16 sm:px-6 lg:px-8 bg-white min-h-[60vh]">
      <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-6 tracking-tight">Legal Disclaimer</h1>
      
      <div className="prose prose-lg text-gray-700 space-y-6">
        <p className="font-medium text-lg border-l-4 border-blue-900 pl-4 py-1 text-gray-900">
          {DISCLAIMER_TEXT}
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mt-8 mb-4">Estimates and Decision Support Only</h2>
        <p className="text-sm sm:text-base">
          The calculators, estimators, and planning tools provided on this application are intended solely for <strong>informational and decision-support purposes</strong>. The results generated by these tools are estimates based on standard rural economic formulas and the accuracy of data points input by users. They do not account for all possible localized variables, market fluctuations, or unique operational constraints.
        </p>

        <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mt-8 mb-4">Independent Verification Required</h2>
        <p className="text-sm sm:text-base">
          We strongly advise all producers, planners, and operators to independently verify any financial projections, break-even analyses, or closeout values before making critical business decisions, signing contracts, or adjusting operational practices. Engage with independent, certified professionals where appropriate.
        </p>
        
        <h2 className="text-xl sm:text-2xl font-semibold text-gray-900 mt-8 mb-4">No Liability</h2>
        <p className="text-sm sm:text-base">
          Rural Utility Cost, its ecosystem subdomains, and its developers shall not be held legally liable or financially responsible for any losses, damages, or enterprise consequences resulting from reliance on these estimation tools. You assume full responsibility and risk for the use of the information and tools provided. Use your best localized judgment.
        </p>
      </div>
    </div>
  );
}
