import React from 'react';

export function LegalView() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16 sm:px-6 lg:px-8 bg-white min-h-[60vh]">
      <h1 className="text-4xl font-bold text-earth-dark mb-6 tracking-tight">Legal & Disclaimers</h1>
      
      <div className="prose prose-lg text-gray-700 space-y-6">
        <div className="bg-orange-50 border-l-4 border-orange-500 p-4 mb-8 text-orange-800 text-sm">
          <strong>Important Notice:</strong> You are currently viewing the legal guidelines derived from the Rural Utility Cost master site, specifically adapted for the Beef hub.
        </div>

        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Estimates and Decision Support Only</h2>
        <p>
          The calculators, estimators, and planning tools provided on this application (the "Beef app") are intended solely for <strong>informational and decision-support purposes</strong>. The results generated by these tools are estimates based on the data points input by users and standard rural economic formulas.
        </p>

        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Independent Verification Required</h2>
        <p>
          We strongly advise all cattle producers, planners, and operators to independently verify any financial projections, break-even analyses, or closeout values before making critical business decisions, signing contracts, or adjusting operational practices.
        </p>
        
        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">No Liability</h2>
        <p>
          Rural Utility Cost and its developers shall not be held legally liable or financially responsible for any losses, damages, or enterprise consequences resulting from reliance on these estimation tools. Use your best localized judgment.
        </p>

        <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4">Privacy Framework</h2>
        <p>
          This app operates primarily client-side. The "My Favorites" list relies strictly on localized browser storage (`localStorage`). We do not harvest, track, or share individual ranch data or operational costs.
        </p>
      </div>
    </div>
  );
}
